# Generated by Django 5.0.6 on 2024-05-26 22:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_alter_habit_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='period',
            field=models.PositiveIntegerField(default=1440, verbose_name='периодичность (минут)'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 26, 22, 5, 29, 565660, tzinfo=datetime.timezone.utc), verbose_name='время'),
        ),
    ]
