# Generated by Django 5.0.6 on 2024-05-27 06:12

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_alter_habit_period_alter_habit_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="period",
            field=models.PositiveIntegerField(
                default=1, verbose_name="периодичность (дней)"
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 5, 27, 6, 12, 22, 990560,
                    tzinfo=datetime.timezone.utc
                ),
                verbose_name="время",
            ),
        ),
    ]
