# Generated by Django 5.0.6 on 2024-05-27 06:16

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0004_alter_habit_period_alter_habit_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="duration",
            field=models.DurationField(
                default=datetime.timedelta(seconds=120),
                verbose_name="время на выполение (секунд)",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 5, 27, 6, 16, 20, 61091, tzinfo=datetime.timezone.utc
                ),
                verbose_name="время (YYYY-MM-DD hh-mm)",
            ),
        ),
    ]
