# Generated by Django 5.0.6 on 2024-05-27 07:49

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0005_alter_habit_duration_alter_habit_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="is_public",
            field=models.BooleanField(
                default=True,
                verbose_name="признак публичности"
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 5, 27, 7, 49, 3, 89143,
                    tzinfo=datetime.timezone.utc
                ),
                verbose_name="время (YYYY-MM-DD hh-mm)",
            ),
        ),
    ]
